### PR TITLE
Add RH commands to Getting Started

### PR DESCRIPTION
**Pull request by blackdwarf**
/cc @ellismg @joshfree

### CODE REVIEW

**Comment by ellismg** [comment]
Does this actually work?  I think the package names differ between apt and yum and I recall needed to do some additional work to get libunwind on centos.

I also suspect that dnvm install is going to pull down the Ubuntu specific binaries and the thing won't even launch.

**Comment by thesmithee** [comment]
The installs work, I've verified it. The DNX being downloaded, as @ellismg suggested, do not work. dnu restore and dnx run don't do anything.

**Comment by ellismg** [comment]
You should remove the backup file (with the ~) from the PR.

**Comment by thesmithee** [comment]
Did in one of the pushes.

**Comment by ellismg** [comment]
Can you try one more thing?  Can you manually download the centos [runtime package](http://www.myget.org/F/dotnet-core/api/v2/package/runtime.centos.7.1-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.1-beta-23504), unzip it to some place, and then replace the `.so` files in the dnx folder with the ones from `runtimes/centos.7.1-x64/native` folder in the package and ensure dnu and dnx launch?

**Comment by ellismg** [comment]
> Did in one of the pushes.

GitHub is still showing some files (the debian one and getting-started one) in their changed files tab, even at 30dd604.

**Comment by thesmithee** [comment]
Argh, forgot the one. This should fix it.

**Comment by thesmithee** [comment]
@ellismg OK, so the trick you gave me worked. dnu and dnx launch (though they are slow?) and at they at least give me an output. dnu restore, however, is very slow, but it works. dnx run is also incredibly slow but it works!

**Comment by ellismg** [comment]
I believe the slowness is due to both the lack of an ngen'd mscorlib and the fact that the runtime is triggering SELinux failures which requires auditing to be written somewhere?  We have bugs tracking both of these issues for RC2.

**Comment by thesmithee** [comment]
Do Ubuntu packages pre-ngen? I didn't see them ngen on install like on Windows.

**Comment by ellismg** [comment]
We don't generate native images on UNIX yet.

**Pull request merged**
