### PR TITLE
Adding new TOC for the conceptual docs

### PR DESCRIPTION
**Pull request by blackdwarf**
/cc @BethMassi

### CODE REVIEW

**Comment by BethMassi** [comment]
I'm seeing inconsistencies with the wrench icon. Sometimes it's showing for topics that are written and sometimes it's not showing for topics that aren't written. Is this a manual thing you have to do or is this part of the build? 

For instance, I'm seeing the wrench on the C# Iterators topic, but it's written. I'm not seeing the wrench on "Writing console applications -> Overview and moving pieces" but the topic is missing.

**Comment by thesmithee** [comment]
This is a manual process, so most likely I screwed up with something. For iterators, I sycned the latest from core-docs and built, and I see that there is still a wrench icon in there (https://github.com/dotnet/core-docs/blob/master/docs/toc.md).

Thanks,
Z

**Comment by BethMassi** [comment]
The wrench is still showing up for the C# iterators article. How do we fix that? Is that up to the contributor of the article?

**Comment by thesmithee** [comment]
Yup. Is that article even merged?

**Comment by BethMassi** [comment]
Yep. Yesterday: https://github.com/dotnet/core-docs/pull/172

It's also showing the wrench in the TOC. So when you write an article, you need to also update the TOC? I think we need clearer contribution guidelines then.

**Comment by thesmithee** [comment]
Yup. _sigh_ I guess I have some PR-ing to do.

**Comment by BethMassi** [comment]
I wish docfx was smart enough to do this on build. If you want me to submit a PR for the contribution guidelines let me know and I can do that one.

**Comment by thesmithee** [comment]
No I will do them all in one fell swoop, but thanks @BethMassi you're the best. The problem is even worse, because you have to change the wrench in three distinct places:
1. In the main TOC
2. In the sub-topic TOC (index.md)
3. In the file

Can get nasty. Say, can you make an issue about this on the core-docs repo as cc @pengbian and @chenkennt? So we have it for tracking.

**Comment by BethMassi** [comment]
Sure will do. I think it could be automated though, yes? I add an issue to docfx repo too.

**Comment by thesmithee** [comment]
I'm not sure that this _can_ be automated easily because the file already exists before someone starts editing it. What would help is a way for the TOCs to be constructed from the headings in the document. In this way, you would remove the "wrench" only from the document you have written and TOC would do the "Right Thing" on building.

**Comment by BethMassi** [comment]
Exactly what I was thinking. It adds a bit of magic, but it's a lot easier for the contribution process. Here's the issue I added to core-docs: https://github.com/dotnet/core-docs/issues/187

**Comment by bleroy** [comment]
Check if that can be useful to you: http://docs.orchardproject.net/Documentation/Installing-Orchard Notice the local document TOC on the side. It looks like what you're asking for. It's generated client-side using this little bit of script:

``` js
;(function($){
    $(document).ready(function(){
        var toc = $(".TocContainer ol")
            .on("mouseenter", function() {
                if (tocOverlay.width() > parent.width()) {
                    tocOverlay.show();
                }
            });

        $("#MainDiv :header")
            .each(function() {
                var $headerTag = $(this);
                var cleanedHeaderFragment = $headerTag.text().replace(/[^A-Za-z0-9\-]/g, "");
                var headerId = getHeaderId(cleanedHeaderFragment);

                $headerTag.attr("id", headerId);

                toc.append(
                    $("<li></li>").append(
                        $("<a/>", {
                            href: "#" + headerId
                        })
                        .append($("<" + this.tagName + "/>", {
                            html: $headerTag.text().replace(/\s/g, "&nbsp;")
                        }))
                    )
                );
            });

        var parent = toc.parent(),
            tocOverlay = parent
            .clone()
            .insertBefore(parent)
            .css({
                overflow: "visible",
                position: "absolute",
                right: "10px",
            }).hide()
            .on("mouseleave", function() {tocOverlay.hide();});
    });

    function getHeaderId(headerFragment, nextIndex) {
        var idToQuery = (nextIndex === undefined ? headerFragment : headerFragment + nextIndex);

        if($("#" + idToQuery).length === 0) {
            return idToQuery;
        }

        if(nextIndex === undefined) {
            nextIndex = 1;
        }

        return getHeaderId(headerFragment, nextIndex + 1);
    }
})(window.jQuery);
```

**Comment by thesmithee** [comment]
Thanks @bleroy. We already have in-document TOC generated. This is more for the outside-in problem. :)

**Comment by bleroy** [comment]
ok, I misunderstood then. :)

**Comment by thesmithee** [comment]
No, no, I will find a use for this code before long. :)

**Comment by thesmithee** [comment]
@BethMassi OK to merge?

**Comment by BethMassi** [comment]
LGTM :shipit:

**Pull request merged**
